indent_style = "Block"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
error_on_line_overflow = true
error_on_unformatted = true
fn_args_density = "Vertical"
format_strings = true
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
merge_derives = true
force_multiline_blocks = true
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
report_todo = "Always"
use_try_shorthand = true
format_doc_comments = true
wrap_comments = true
edition = "2018"